### PR TITLE
Feature/delete confirming validators after complete

### PR DESCRIPTION
**Pull request by cducrest**
Gas costs for a transfer with 50 validators, require 50% to complete transfer, and no validator set changes:

### with optimization:

first confirm: 97_156
other confirm: 82_156
last confirm: 169_808
useless confirm: 28_234

total confirm: 2_156_552

### without optimization:

first confirm: 97_156
other confirm: 82_156
last confirm: 217_578
useless confirm: 28_234

total confirm: 2_204_322

### CODE REVIEW

**Comment by berndbohmeier** [comment]
Any idea why the gas cost of a confirm do not change even though we removed:
` transferState[transferStateId].numConfirmations += 1;`?

**Comment by berndbohmeier** [comment]
The mapping and the list belong together, so did you try to clear also the mapping, maybe that also saves gas?

**Comment by cducrest** [comment]
You can't delete a mapping since it does not know which key has an actual set value, so we'd need to loop over all the validators and delete the value of `isConfirmedByValidator[validator]`. This increases gas costs by 100k.

**Comment by berndbohmeier** [comment]
Can you somewhere post the test code?
I mean cleaning a slot should refund 15k, so I dont get why this does not work.

**Comment by cducrest** [comment]
there it is: https://github.com/trustlines-protocol/blockchain/compare/feature/clean-is-confirmed-mapping?expand=1

I don't fully understand how mappings work internally, but afaict in the struct it is just one word, and each bool is on bit. So not so much storage freed by deleting it.

**Comment by schmir-at-bb** [comment]
I'm looking into this.

**Pull request merged**
