### PR TITLE
Author Address

### PR DESCRIPTION
**Pull request by jannikluhn**
Closes https://github.com/trustlines-protocol/blockchain/issues/532

It doesn't work right now. I get the error "Unkown argument: --author" from parity. I'm not sure what's wrong: I checked that the environment variables are configured properly and from there on I just do the same for "author" as is already done for "validator". "author" is the right name according to the documentation and the changelog doesn't mention it, so it shouldn't have been renamed.

Could this the same issue you encountered, @berndbohmeier ?

### CODE REVIEW

**Comment by schmir-at-bb** [comment]
same error, yes. fix has been merged to master in c7b11cc.

**Comment by jannikluhn** [comment]
The error persists even after rebasing, so it seems to be a separate issue. Investigating...

**Comment by jannikluhn** [comment]
This seems to work now, but requires both the blockchain image to be rebuilt (as the wrapper script was updated).

**Comment by schmir-at-bb** [comment]
So, by default we burn the block rewards on the zero address?

**Comment by jannikluhn** [comment]
No, by default it goes to the validator address (https://github.com/trustlines-protocol/blockchain/pull/543/files#diff-9aa8e06f1aece82472dc89a029529a57R161). The zero address is only used for non-validators so that the parity wrapper has a valid argument to parse.

**Comment by berndbohmeier** [comment]
Working on it

**Pull request merged**
