### PR TITLE
Upload bridge validator docker image with circleci

### PR DESCRIPTION
**Pull request by weilbith**
After all the _CircleCI_ extensions are just re-using existing jobs. This kinda bloats the configuration, but keep it clear and avoids mistakes on optimizations (which aren't even working well).
The release strategy follows the suggestion in #301. The only thing that has changed is the cleaning of the branch name for the docker tag. Since we have now multiple release branches which can be prefixed (e.g. `bridge/pre-release`), this does not work as it is anymore (`trustlines/bridge-next:bridge/pre-release` is not validly tagged).
Moreover I have adjusted the docker compose setup to make use of this image for a production setup. This required a restructuring of the `.yaml` files.

Close: #301

### CODE REVIEW

**Comment by weilbith** [comment]
@saschagoebel I assigned you as first reviewer, because Ralf has a lot to do and you could verify at least the docker-compose and README part.

**Comment by weilbith** [comment]
Yes and I think it should be restricted to the release branch only. On any other this does not matter. Pushing a pre-release to satisfy the tests sound awkward to me.

**Comment by schmir-at-bb** [comment]
Can we please test this on the bridge/pre-release and bridge/release branch?(i.e. you should push to those branches).

Which repos do I have to create on dockerhub?

**Comment by weilbith** [comment]
@schmir-at-bb yes of cause.

> Which repos do I have to create on dockerhub?

- `bridge-next`
- `bridge`

This are the names you suggested :wink: I'm open for renaming. 
But do you need to create them first? Doesn't pushing with a new name just initialize a repository? :thinking:
Ping me if they exist, then I push to the other branches. :+1:

**Comment by schmir-at-bb** [comment]
Let's merge this. We still need to figure out what to do with the image diffing...

**Pull request merged**
