### PR TITLE
Use Marshmallow for configuration

### PR DESCRIPTION
**Pull request by jannikluhn**
What I have not done (yet):

- group config entries: We want to have home chain and foreign chain config groups, so that we can share schemas there. They are not exactly equal though and I didn't find a way to extend schemas.
- validate the logging config: We haven't been doing it so far, but it might be useful. Future PR?

### CODE REVIEW

**Comment by jannikluhn** [comment]
now rebased and including webservice config

**Comment by schmir-at-bb** [comment]
> validate the logging config: We haven't been doing it so far, but it might be useful. Future PR?

My guess is that this isn't easy. I would not try it.

**Comment by schmir-at-bb** [comment]
I've pushed some changes to your branch. Please try to use pre-commit. If it doesn't work on your machine, please complain!

**Comment by schmir-at-bb** [comment]
> They are not exactly equal though and I didn't find a way to extend schemas.

Can you use a subclass with additional fields?

**Comment by jannikluhn** [comment]
Yep, that probably works. Wonder how I didn't think of this, sounds quite natural...

**Pull request merged**
