### PR TITLE
Confirmation task planner take two

### PR DESCRIPTION
**Pull request by jannikluhn**
Cf. #259 

Tried to incorporate @schmir-at-bb suggestions, but I don't think I understood exactly what they were and I like this even less than the first version. We should have a call on this tomorrow.

### CODE REVIEW

**Comment by schmir-at-bb** [comment]
I'll try to take a look at it today and we could have a call on this tomorrow.

**Comment by jannikluhn** [comment]
> I still do not get why we need the all these timestamps. But I'm fine with keeping it this way, I guess this will get clear to me with the followup PR.

We need some notion of time to know
- up to which point the two chains are synchronized
- at which time we can forget about stale events
- to be able to give the home chain some time after transfer events to produce confirmation/completion events

Block numbers don't work as they are not synchronized between the two chains.

**Comment by schmir-at-bb** [comment]
> * up to which point the two chains are synchronized

What does that mean?

> 
> * at which time we can forget about stale events

What are stale events? If there is a transfer we either have to confirm it, or it is already confirmed or we did already confirm it.


> 
> * to be able to give the home chain some time after transfer events to produce confirmation/completion events

Here we can use the local time on the machine from what I can tell.

**Comment by jannikluhn** [comment]
> > * up to which point the two chains are synchronized
> 
> What does that mean?

We see a transfer event at time `t`. If we have to confirm it or not depends on if there's a conf/comp event some time after that. To know this, we need to be sure that the home chain has synchronized at least until `t + HOME_CHAIN_LOOKAHEAD`.

> > * at which time we can forget about stale events
> 
> What are stale events? If there is a transfer we either have to confirm it, or it is already completed or we did already confirm it.

I just mean events that have no meaning for us anymore but we still keep track of them. Most common will probably be a combination of transfer+confirmation event. We should not delete the two before observing the completion event because otherwise we'd end up with a stale completion event. Other example could be a confirmation event by a rogue validator for a transfer that doesn't exist.

> > * to be able to give the home chain some time after transfer events to produce confirmation/completion events
> 
> Here we can use the local time on the machine from what I can tell.

Maybe, I don't quite know what you have in mind here, but that information would still have to come from the event fetcher, presumably via the event queue, and I don't see how this would be any simpler.

**Comment by schmir-at-bb** [comment]
> ``.



> We see a transfer event at time `t`. If we have to confirm it or not depends on if there's a conf/comp event some time after that. To know this, we need to be sure that the home chain has synchronized at least until `t + HOME_CHAIN_LOOKAHEAD`.

When we are in sync with the home chain, i.e. we have 'recorded all events, we can check if we have seen a completed event or if we have seen a confirmation event from ourselves (in case we forgot the latter). That's the point of introducing  the artificial event 'synced with chain'. I don't think the HOME_CHAIN_LOOKAHEAD is necessary.

**Comment by jannikluhn** [comment]
At the very least the artificial event would need a timestamp, otherwise it could be that the artificial event is outdated (i.e. the chain was synced at some point in the past, but is not anymore). And I doubt the code would get any simpler if we had proper events without and artificial events with timestamp.

Agree that the `HOME_CHAIN_LOOKAHEAD` is not strictly necessary, but it's nice to have. It also might make future improvements easier, in particular we could introduce a random lookahead to avoid >50% confirmations.

**Comment by schmir-at-bb** [comment]
> At the very least the artificial event would need a timestamp, otherwise it could be that the artificial event is outdated (i.e. the chain was synced at some point in the past, but is not anymore). 
> And I doubt the code would get any simpler if we had proper events without and artificial events with timestamp.

The code would get simpler because we could get rid of all the timestamp handling. The problem is not the additional field in the events. The problem is that we do the timestam handling in the confirmation planner. The confirmation_task_planner is full of this timestamp handling. At the moment I don't see why we need this. Let me repeat myself:

If we are synced with the home chain, we can send out confirmations for every transfer that we have seen on the foreign chain up to this point, in case we did not already sent out a confirmation and we didn't see a  completion event for the transfer.  You don't need any timestamps for that.

Either the above statement is wrong or your implementation is too complicated. In the first case, please explain to me why it is wrong, in the second case, please change the implementation and get rid of the timestamp handling.

> Agree that the HOME_CHAIN_LOOKAHEAD is not strictly necessary, but it's nice to have. It also might make future improvements easier, in particular we could introduce a random lookahead to avoid >50% confirmations.

I'm not sure what your plan is. But I'd rather keep it simple.

**Comment by jannikluhn** [comment]
> If we are synced with the home chain

how do we know that we are synced without a timestamp? If it's just a "you are synced now" on the queue, this information could be outdated.

**Comment by schmir-at-bb** [comment]
> > If we are synced with the home chain
> 
> how do we know that we are synced without a timestamp? If it's just a "you are synced now" on the queue, this information could be outdated.

We know we are synced with the home chain, when we have fetched till the latest block and there are no new events. We put the artificial event on the queue and can even give it a timestamp. If we fail to process the event in the next say 2s we ignore it.
The fact that we use a timestamp for this one event, doesn't mean we need all the complexity that we have now.

**Pull request merged**
